### ISSUE TITLE
Ubuntu 14.04/14.10/15.04 can only use 'quota' command, all others fail.

### ISSUE THREAD

**Issue by Copytalky** [yadayada/acd_cli#105]
I have tested on various VPS providers 14.04, 14.10, 15.04 images and have only found one VPS provider which this script installs and runs on.

I get the following error message when using acd_cli:

root@CTUSC:~# acd_cli ls /
15-08-04 21:59:06.421 [CRITICAL] [acd_cli] - Could not resolve path "/".

quota command works fine. All other commands produce similar results of CRITICAL error.

pip/pip3 is working.

root@CTUSC:~# pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
root@CTUSC:~# pip3 -V
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)

Linux CTUSC 3.16.0-45-generic #60~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I've found that on 14.10/15.04 trying to get pip3 to work has resulted in many failures, it turned out that you need to do 'sudo' with 14.10/15.04 to get pip3 command to work on some VPS images.

Any word on what's causing this CRITICAL issue on some images?

I have one 14.04 provider which the install went smooth on, however every time i try to upload files, I think their system auto shuts down my VPS after a while because it's utilizing so much bandwidth with the test files I'm transferring. (tested 3G binary file and was able to get to 48% first time then 62% second time before server was not responsive via ssh or remote-console login, had to reboot.) Haven't had any emails from the VPS provider stating that the VPS was abusing speed so I'm not sure if it was them who stopped the transfers/halted the VPS.

**Comment by msh100** [comment]
I can tell you with absolute confidence this isn't an Ubuntu issue. I am a heavy user of a acdcli and I only use Ubuntu LTS. I have successfully installed multiple times over different providers.

Sent from my iPhone

On 5 Aug 2015, at 03:06, worlddev <notifications@github.com<mailto:notifications@github.com>> wrote:


I have tested on various VPS providers 14.04, 14.10, 15.04 images and have only found one VPS provider which this script installs and runs on.

I get the following error message when using acd_cli:

root@CTUSC:~# acd_cli ls /
15-08-04 21:59:06.421 [CRITICAL] [acd_cli] - Could not resolve path "/".

quota command works fine. All other commands produce similar results of CRITICAL error.

pip/pip3 is working.

root@CTUSC:~# pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
root@CTUSC:~# pip3 -V
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)

Linux CTUSC 3.16.0-45-generic #60<https://github.com/yadayada/acd_cli/issues/60>~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I've found that on 14.10/15.04 trying to get pip3 to work has resulted in many failures, it turned out that you need to do 'sudo' with 14.10/15.04 to get pip3 command to work on some VPS images.

Any word on what's causing this CRITICAL issue on some images?

I have one 14.04 provider which the install went smooth on, however every time i try to upload files, I think their system auto shuts down my VPS after a while because it's utilizing so much bandwidth with the test files I'm transferring. (tested 3G binary file and was able to get to 48% first time then 62% second time before server was not responsive via ssh or remote-console login, had to reboot.) Haven't had any emails from the VPS provider stating that the VPS was abusing speed so I'm not sure if it was them who stopped the transfers/halted the VPS.

-

**Comment by yadayada** [comment]
Soo... have you synced prior to using the list command?

**Comment by Copytalky** [comment]
@msh100 I realize it isn't per say a ubuntu issue likely but rather the VPS providers images. I've read that pip3 requires 'sudo' with some providers images, I found that to be the case when running the pip3 command to pull the upgrade/git on some images, otherwise pip3 would crap out with a bunch of errors.

I was able to successfully upload a file on my working VPS, where otherwise it would completely halt the system prior when using dummy test binary files i generated with fallocate. I tried lowering the size of the test file and it still wouldn't upload properly to amazon. I had to upload a real file (chose a mkv 400mb file) to my VPS then try uploading it to amazon, that worked.


On the other VPS where I get the critical issue, what information do you need for troubleshooting? I couldn't find a log file.

**Comment by Copytalky** [comment]
Why is this closed? I had requested for information regarding what troubleshooting data you require. where would the logs be that will show the 'critical' error so I can provide the troubleshooting data?

**Comment by msh100** [comment]
try 

```
acd_cli -d ls /
```

**Comment by Copytalky** [comment]
root:~# sudo acd_cli -d ls /
15-08-07 23:36:03.515 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-08-07 23:36:03.515 [INFO] [acd_cli] - TestPlugin attached.
15-08-07 23:36:03.516 [INFO] [acdcli.cache.db] - Initializing cache with path "/root/.cache/acd_cli".
15-08-07 23:36:03.536 [INFO] [acdcli.cache.db] - Cache not considered uninitialized.
15-08-07 23:36:03.539 [INFO] [acdcli.cache.db] - DB schema version is 1.
15-08-07 23:36:03.555 [CRITICAL] [acd_cli] - Could not resolve path "/".

same issue as when i don't use sudo.

**Comment by msh100** [comment]
As yadayada said. Are you sure you did `acd_cli sync` beforehand?


Sent from my iPhone

On 8 Aug 2015, at 00:36, worlddev <notifications@github.com<mailto:notifications@github.com>> wrote:


root:~# sudo acd_cli -d ls /
15-08-07 23:36:03.515 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-08-07 23:36:03.515 [INFO] [acd_cli] - TestPlugin attached.
15-08-07 23:36:03.516 [INFO] [acdcli.cache.db] - Initializing cache with path "/root/.cache/acd_cli".
15-08-07 23:36:03.536 [INFO] [acdcli.cache.db] - Cache not considered uninitialized.
15-08-07 23:36:03.539 [INFO] [acdcli.cache.db] - DB schema version is 1.
15-08-07 23:36:03.555 [CRITICAL] [acd_cli] - Could not resolve path "/".

same issue as when i don't use sudo.

-

**Comment by Copytalky** [comment]
ah that appears to have done it.. -_-
what i did before was copy the oauth_data contents from one vps to another thinking all it would need on startup is the file then would be ok. I believe on this vps i never did acd_cli sync. now that I did sync (without clearing the oauth_data file) the sync shows:

root:~# acd_cli sync
Syncing...
Done.

and now other commands appear to work:
root:~# acd_cli ls /
[54fBy9NcTEqZqMAcieUpTw] [A] Documents/
[2nWhGNoxQ3mei5L89O4w9Q] [A] Pictures/
[4TVWNGd2Qj6j88TqRv_gWQ] [A] Videos/


I noticed the quota command appears to not work properly, however that's a different issue.
root:/tmp# acd_cli quota
{
    "available": 109951162777600,
    "benefits": [],
    "grants": [],
    "lastCalculated": "2015-08-08T00:13:20.040Z",
    "plans": [
        "CDSPUS0000"
    ],
    "quota": 109951162777600
}

I know I have 400mb file on amazon cloud drive currently so not sure why quota is showing that there's 100% free space.
