### ISSUE TITLE
Differences in transfer speed when using fuse mount

### ISSUE THREAD

**Issue by seppi91** [yadayada/acd_cli#112]
I noted that there are differences in speed when using Fuse in combination with rsync instead when using 'acd_cli download' command. When using Fuse with rsync i get rates between 0.5 - 2 MB/s. With 'acd_cli download' i'm observing much higher speeds (20-30 MB/s). I am connected with a gbit connection, so bandwidth shouldn't be an issue.

Can the performance over fuse be improved or are there any restrictions from fuse module?

**Comment by yadayada** [comment]
I think the multi-threaded read may not be working as expected for some reason. Please try the `-st` argument to get a more consistent (and higher) transfer speed.

**Comment by HazCod** [comment]
And try with a `cp` instead of rsync. Or at least try `rsync -avh`, so it doesn't checksum Evert filechunk.

**Comment by seppi91** [comment]
@yadayada Thank you for the single threaded suggestion, it increases the rate to 9,13MB/s
@HazCod Just changing the rsync command from -avP to -avhP didn't make any difference.

**Comment by jamesrascal** [comment]
I am also experiencing this same issue. Fuse mounted drives are only copying the files at 200kbs-2Mbps. Any suggestions on fixing while using a mount?

**Comment by ttk2** [comment]
the -st argument seems to have been removed as mount will no longer accept it, is there a new option we should be using to make uploading reasonably fast?

**Comment by yadayada** [comment]
I briefly set the default mode to single-threaded, removed the -st argument, but I re-added it in commit 050156ec20c23bb360ff68adcf8f1a17b0aea571. Anyway, you are getting the fastest FUSE upload speed possible.

**Comment by HazCod** [comment]
To get on this; `acdcdi upload foo bar` gives me around 20MB/s, while with mount (`acdcli mount acd/) it hovers around 10MB/s.

**Comment by seppi91** [comment]
@yadayada just to clear things up: You said "we are getting the fastest FUSE upload speed possible.", does this mean the fuse transfer speed of the current revision is the highest possible rate we will see in near future? Why is fuse slower than using 'acd_cli ul'?

**Comment by yadayada** [comment]
I merely meant that the ``-st `` flag is no longer necessary to get the highest read speed.

>Why is fuse slower than using 'acd_cli ul'?

The simple ``ul`` action reads and uploads a local file and a FUSE upload is much more complicated. It creates a WriteStream object that gets written into by the file system (usually in 512b or 4K chunks) and gets read from by a thread for streamed upload. The bytes in the WriteStream are held by a Queue, which may be a tad inefficient.

Either way, there is not much speed difference I can detect with *my* 50Mbit connection. So, it's not much use for me to fiddle around if I cannot benchmark anything...

It might be easier to parallelize rsync.

I'm closing the issue because the original multi-threaded read speed bug was fixed and I hope this comment answers your question.
