### ISSUE TITLE
Add configuration files

### ISSUE THREAD

**Issue by yadayada** [yadayada/acd_cli#171]
Create a settings path in which hard-coded constants may be overridden in INI files (https://docs.python.org/3.2/library/configparser.html).

- [x] ACD API: connection time-outs, chunk size, ...
- [ ] ~~CLI: log size~~
- [x] FUSE: buffer (queue) size, active chunks per file, timeouts
- [ ] document the settings

**Comment by zmwangx** [comment]
Before (potentially) having another dotfile dropped into my `HOME`, here's a friendly reminder about the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). I and many others would be truly grateful if `$XDG_CONFIG_HOME` is respected, or at least having `~/.config/acd_cli/` as an option.

**Comment by yadayada** [comment]
I'm always annoyed when applications pollute the home directory. So I chose to use [appdirs](https://github.com/ActiveState/appdirs) to get sensible defaults for cache and config paths for the common OSes.

**Comment by zmwangx** [comment]
That's certainly better than polluting `$HOME`, and I know people's opinions differ on this, but I would prefer XDG on OS X too, since to me `~/Library/Application Support` (read *Application* support) are really for bundled application, whereas CLI software packages should follow the Unix traditions, just like bundled applications live in `/Applications` whereas `~/Applications` while CLI software packages live in `/usr/local`. (In this case the Unix tradition is to litter the homedir which is really distasteful, so the less traditional yet still very popular XDG Base Dir Spec seems like a good common ground.)

Could XDG be made an option on OS X also? With PSL `configparser` it's really just four more lines:

```python
# config = configparser.ConfigParser()
# configfiles = [...]

if 'XDG_CONFIG_HOME' in os.environ and os.environ['XDG_CONFIG_HOME'] != '':
    configpaths.append('%s/acd_cli/conf.ini' % os.environ['XDG_CONFIG_HOME'])
else:
    configpaths.append(os.path.expand_user('~/.config/acd_cli/conf.ini'))

# config.read(configfiles)
```

Or there could be an env var like `$ACD_CLI_CONFIG_PATH`, but then we would carry that signature in every single command, which even counts toward `$ARG_MAX`, so not very nice.

P.S. `~/Library/Application Support` even has a space in its path, making it very distasteful.

**Comment by zmwangx** [comment]
Another case for `$XDG_CONFIG_HOME`, or `$HOME/.config`: this single directory of config files can be easily versioned and backed up. As for `~/Library/Application Support`, there're tons of crap there, most of there binary.

**Comment by yadayada** [comment]
I will stick to whatever directory appdirs determines. For people who don't like that for some reason, there already is an environment variable ``ACD_CLI_SETTINGS_PATH`` devised for overriding the path.

**Comment by zmwangx** [comment]
Sure, that will work.
