### ISSUE TITLE
Crontab acd_cli bash script

### ISSUE THREAD

**Issue by 2marshall** [yadayada/acd_cli#197]
I have created a bash script and pointed a crontab entry at it. I see the crontab entry executing in the syslog file but the acd_cli logging doesn't show entries during that crontab window. It looks like it isn't running.

Is there a recommended way to bash script this acd_cli and create a crontab entry for it that will work?

thanks

**Comment by breunigs** [comment]
are you looking at the right user? I.e. if you run the crontab script as root, you need to check `~root/.cache/acd_cli/` instead of /your/ home folder. 

are you sure the path is recognized correctly under crontab? I.e. is your script picking up your `.bash_profile` or other files, where you set your `$PATH` to include `/usr/local/bin` most likely. In that case, maybe an absolute path to `acd_cli` helps?
