### ISSUE TITLE
Files are truncated during upload, yet no error is reported.

### ISSUE THREAD

**Issue by r-a-i** [yadayada/acd_cli#234]
Hi, 
I'm uploading a set of photos (JPG, CR2 mainly) to Amazon Cloud Drive in a batch and the images seem to be only partially uploaded.  More specifically, when looking at the resulted uploads, and then when downloading the files back, all JPG images come back being about 1/2 the original size and look like the half the data is gone (as a gray/white section of the image). 

I'm uploading from Ubuntu 14.04 running by running: acd_cli upload /photos_dir/year /Photos/

Anybody else seeing partial file uploads?

**Comment by yadayada** [comment]
I could not reproduce this problem with Ubuntu 14.04.

Which VPS provider are you using?

**Comment by msh100** [comment]
I am curious, are you using the Unlimited Everything plan or the Cloud Drive photo-only plan?

**Comment by r-a-i** [comment]
Hi, no VPS. This is a self-owned Ubuntu box at home behind a Cable (TimeWarner) connection. 

Yes. I'm using the "Cloud Drive photo-only" plan.

Would you like to look a the logs?

**Comment by zmwangx** [comment]
Interesting, recently (last three weeks or so) I've been on a mediocre ~100Mbps Wi-Fi connection and also hit this problem. Small files (<1MB) are uploaded fine, but every single relatively large file (like a few hundred MBs) is truncated about exactly halfway. No error reported (I thought acd_cli compares local MD5 to remote MD5 when upload finishes, no?). I haven't tested any file size in between, and haven't investigated this issue. I'll be back to a good ~1Gbps Ethernet connection in a few days, and will see if I can reproduce over there.

**Comment by yadayada** [comment]
Still no idea by what this could be caused. 

>I thought acd_cli compares local MD5 to remote MD5 when upload finishes, no?

The checksum is calculated on the fly when reading the file as it is being uploaded. If the upload finishes prematurely and no errors occurred, these checksums will match.

**Comment by zmwangx** [comment]
> The checksum is calculated on the fly when reading the file as it is being uploaded. If the upload finishes prematurely and no errors occurred, these checksums will match.

That explains it. Maybe a length check should be added? It adds minimal overhead, and coupled with MD5 it basically eliminates any possibility of corrupted upload.

**Comment by zmwangx** [comment]
Submitted PR #236 to do the length (size) check.

**Comment by yadayada** [comment]
Could you please try the last version that used libcurl for file transfer (https://github.com/yadayada/acd_cli/tree/17c0407ca2f2668c7a34e3945bf45483548ee858) and check whether the files get entirely uploaded?

**Comment by zmwangx** [comment]
I didn't try the libcurl version because I didn't want to build a >500M v1 database all over again :wink: However, I suspected `requests` and upgraded `requests` 2.9.0=>2.9.1 and `requests-toolbelt` 0.5.0=>0.5.1; now everything's working again. I checked `requests` on my other machine which was known to upload correctly (but haven't been used for the last couple of weeks) and it's still on 2.8.1, so the regression must have been introduced in 2.9.0.

Now, looking at 2.9.1 change log, it says

> Resolve regression introduced in 2.9.0 that made it impossible to send binary strings as bodies in Python 3.

But how exactly MultipartEncoder managed to bypass the impossibility and upload *exactly* half of each file is beyond me, without delving into the source code. Anyway, case closed, as long as @r-a-i could confirm.

**Comment by r-a-i** [comment]
Hi. I'm afraid I'll need a little hand holding here as I'm no Python 'power user'.  I see I have 'requests 2.9' in "/usr/local/lib/python3.4/dist-packages/requests-2.9.0.dist-info".   I tried "sudo pip3 install requests --upgrade" but It still kept it at 2.9.0.  Can you share a how-to or pointer to upgrade this packages?

**Comment by zmwangx** [comment]
What do you see in `pip3 freeze`? `requests==2.9.0` or `2.9.1`?

`dist-packages` seems to be a Debian-specific thing; I suppose you installed requests through the apt package `python-requests`? I have little knowledge of how apt manages python packages and I don't have time to test now, so I'm afraid I can't help. Anyway, I suggest you use a [virtualenv](https://virtualenv.readthedocs.org/en/latest/) instead. Run `python3 setup.py install` or `python3 setup.py develop` inside your virtualenv, and requests 2.9.1 should be automatically installed.

**Comment by r-a-i** [comment]
I also upgraded the requests-toolbelt now and I see:
After upgrading only 'requests' to 2.9.1 I still saw truncated images. Then I also upgraded requests toolbox and now I see:
$ pip3 freeze | grep request
requests==2.9.1
requests-toolbelt==0.5.1

Restarted upload and initial images are looking good!  I'll confirm later if this fixes the issue for even larger images.

**Comment by r-a-i** [comment]
Larger RAW images are now uploading completely.  The set is large so it will take days to upload but I think it is reasonable to call this done.  Thank you very much for your prompt help in resolving this!

**Comment by urandom** [comment]
Hi,

I'm still getting the occasional broken image. I've been running with an older version of acd_cli for a while and noticed that all jpegs were only partially uploaded (no exceptions). After finding this bug, I got the latest version from git a couple of days ago, and I've been force-overwriting all images (with -f) because I wasn't sure whether they would get reuploaded otherwise. That being said, I noticed that a few images were still only half-uploaded. What's worse, without the force flag, acd_cli would gladly skip then since it thinks they are the say, when the size reported by the web ui is exactly half of the real image (web ui - 2.6 MB, ls -sh - 5.2M). And the reason for skipping is this:

```Skipping upload of "IMG_7704.jpg" because of mtime or ctime and size.``` - even though the size is clearly different. Is there anything else I'm missing. Am I supposed to somehow do a special sync or pass a special flag when uploading to force acd_cli to compare sized properly?

And since these things were discussed above: requests - 2.10, requests-toolbelt - 0.6.2

**Comment by yadayada** [comment]
I think the overwrite flag provides a sane and safe behaviour. Also, "incomplete" uploads do not happen under normal circumstances, meaning there is no point in trying to detect them. A higher remote time usually means the remote file is newer.

>And since these things were discussed above: requests - 2.10, requests-toolbelt - 0.6.2

Would you care to clarify??
