### ISSUE TITLE
Simple (stupid) fix for 401 errors -- works for me, anyway

### ISSUE THREAD

**Issue by xiojason** [yadayada/acd_cli#332]
In backoff_req.py I added one line to this function:

```
    def _wait(self):
        with self.__lock:
            duration = self.__next_req - time.time()
        if duration > 5:
+           self.auth_callback.refresh_auth_token()
            logger.warning('Waiting %fs because of error(s).' % duration)
        logger.debug('Retry %i, waiting %fs' % (self.__retries, duration))
        if duration > 0:
            sleep(duration)
```

Since then, I have not seen the token issue mentioned in #326, #328, and #330.

**Comment by EldonMcGuinness** [comment]
Figured I would give it a try, didn't work for me or two separate boxes.

**Comment by sergiopatino** [comment]
This is working for me so far... 

### Reading files until token expires:
16-05-26 03:01:48.790 [DEBUG] [acdcli.acd_fuse] - -> read /.media/ECRYPTFS_FNEK_ENCRYPTED.FWbmmfcYCUeT.EYgMEESxHH1wMkPbSsRK9DxOmm4-ekJQATV2O9zLVnK.E--/ECRYPTFS_FNEK_ENCRYPTED.FYbmmfcYCUeT.EYgMEESxHH1wMkPbSsRK9DxE7EWXYpLFO9BV5jT3X3Xv3EZ25.l6CPlCvNIcZkqTMgbL2GJ1cEGVOdSxi4HQ2FW (16384, 0, 139)
16-05-26 03:01:48.798 [DEBUG] [acdcli.api.content] - chunk o 0 l 524288000
16-05-26 03:01:48.798 [DEBUG] [acdcli.api.backoff_req] - Retry 4, waiting 4.235962s
16-05-26 03:01:53.039 [INFO] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/jQGNAKifR7Gq3irRqs7jOg/content"
16-05-26 03:01:53.093 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/jQGNAKifR7Gq3irRqs7jOg/content HTTP/1.1" 401 89
**16-05-26 03:01:53.094 [ERROR] [acdcli.acd_fuse] - get: RequestError: 401, {"logref":"32c41205-22ee-11e6-8961-49a6bc551561","message":"Token has expired","code":""}**
16-05-26 03:01:53.095 [DEBUG] [acdcli.acd_fuse] - <- read 21
16-05-26 03:01:53.096 [DEBUG] [acdcli.acd_fuse] - -> read /.media/ECRYPTFS_FNEK_ENCRYPTED.FWbmmfcYCUeT.EYgMEESxHH1wMkPbSsRK9DxOmm4-ekJQATV2O9zLVnK.E--/ECRYPTFS_FNEK_ENCRYPTED.FYbmmfcYCUeT.EYgMEESxHH1wMkPbSsRK9DxE7EWXYpLFO9BV5jT3X3Xv3EZ25.l6CPlCvNIcZkqTMgbL2GJ1cEGVOdSxi4HQ2FW (4096, 0, 139)
16-05-26 03:01:53.101 [DEBUG] [acdcli.api.content] - chunk o 0 l 524288000

### Token refreshes after waiting:
**16-05-26 03:01:53.101 [INFO] [acdcli.api.oauth] - Refreshing authentication token.**
16-05-26 03:01:53.103 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): tensile-runway-92512.appspot.com
16-05-26 03:01:53.341 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST / HTTP/1.1" 200 1385
**16-05-26 03:01:53.345 [INFO] [acdcli.api.oauth] - New token expires at 2016-05-26 03:59:53.101945.**

### Following retry is successful:
16-05-26 03:01:53.350 [WARNING] [acdcli.api.backoff_req] - Waiting 14.786142s because of error(s).
16-05-26 03:01:53.351 [DEBUG] [acdcli.api.backoff_req] - Retry 5, waiting 14.786142s
**16-05-26 03:02:08.152 [INFO] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/jQGNAKifR7Gq3irRqs7jOg/content"
16-05-26 03:02:09.366 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/jQGNAKifR7Gq3irRqs7jOg/content HTTP/1.1" 206 524288000**
16-05-26 03:02:09.367 [DEBUG] [acdcli.api.backoff_req] - x-amzn-RequestId: c77bb29d-e2d8-48f4-a1de-e8463f5872aa
16-05-26 03:02:09.367 [DEBUG] [acdcli.acd_fuse] - <- read 4096

**Comment by hjone72** [comment]
I am also finding this has resolved the issue. Nice find!

**Comment by combwizard** [comment]
Yeah, this seems to have worked for me as well. Here's a big thank you, @xiojason (before this, too, is locked)!

@EldonMcGuinness What I did was make the changes to the .py, then delete the oauth_data file, do a _acd_cli -v init_ to grab a new token, and lastly reboot my server. I don't know if all those steps are necessary, but it is what worked for me.

**Comment by Endym10n** [comment]
@EldonMcGuinness First a Big think you for this "ugly" fix its now working
@combwizard Thank you for you short description of what you did. A restart of the server did it for me and and im now scanning my PLEX libraries withiout any hassle.

**Comment by mpk99** [comment]
Tried this and i'm still getting the error -- just so frustrating that this has taken so long to be addressed.  Thanks for trying.

**Comment by GertlilyNL** [comment]
This little line fixed the problem for me, at first it didn't work. But after a reboot it was ready to go and no issues since. 

**To everyone, add that line to the file, after that reboot and that should work.**

**Comment by icenine9** [comment]
Didn't work for me (for long) - though it's an improvement. After a while I could see the directory entries, but the same 401 errors prevent you from getting to the actual content after a certain amount of filesystem activity.

**Comment by mpk99** [comment]
i added that line and rebooted -- still same error for me, didn't fix it.

**Comment by chauffer** [comment]
Works for me! :+1:

Make sure to remove the pycache files for the files you edit.

**Comment by mpk99** [comment]
and after i've removed the pycache files then what? i removed it and now acd doesn't work at all for me...

**Comment by yadayada** [comment]
For fuck's sake, people. Go to the Gitter chat if you have to.
