### ISSUE TITLE
File listing slow for fuse mount

### ISSUE THREAD

**Issue by makkus** [yadayada/acd_cli#339]
Sorry, I'm not sure whether this is an issue with acd_cli, or with my setup. But I can't make head or tails of what I'm seeing at the moment, so I figured somebody on here might be able to help me.

On a Debian Jessie VM I've got a folder with about 2000 files on Amazon, and I mount my (whole) cloud drive using acd_cli/fuse with systemd (ala: ExecStart=/usr/local/bin/acd_cli mount --foreground --allow-other /mnt/amazon ). 

So, whenever I try to ls the folder with the 2000 files as normal user, it takes ages for the ls command to finish. When I do the same command as root, it lists the content of that particular folder instantly. When I do the ls command as normal user using plain "acd_cli ls" there is no issue at all.

As if that wasn't funny enough, on a different machine (also VM, also using Debian Jessie, but might have some special settings since it's a NAS distribution) the same setup and the same ls command returns immediately (successfully), both as root and normal user.

On both machines though, if I do a "ls -l" instead of a plain "ls" the command never finishes, or at least takes so long that I can't wait for it to finish. A normal "acd_cli ls -l" works fine on that folder, for both root and non-root.

Anybody any idea what could be wrong? Or at least where I could start looking for the culprit?

Thanks!

**Comment by breunigs** [comment]
It is instructive to tail acdcli’s logfile while doing an `ls` or an `ls -l`. I'm not sure why just `ls` takes that long for you, but in case of `ls -l` it first requests a list of all files, i.e. the same thing `ls` does. Then it goes on to request metadata for each file individually. Are you sure there is not something more going on than plain `ls` with your user account? Try running `\ls` and see if that speeds things up.

As far as I have researched this is how the fuse API works, unless you implement support for `readdirplus`. That command would more or less batch request all metadata, instead of doing n+1 queries. Take that with a grain of salt, though. I didn’t find a lot of documentation and I couldn’t get fuse to even try to query for `readdirplus`.

**Comment by makkus** [comment]
Right. '\ls' worked fine. Good catch, thanks heaps. Turns out I had an alias ls='ls --color=auto' on the user account on the 'slow' machine.

I guess since I don't have control over which attributes the application(s) that use the data request, I'll try to split up my folder into subfolders, and not have more than, say, 100 items in each.

Thanks again!
