### ISSUE TITLE
Unstable speed up/down

### ISSUE THREAD

**Issue by Issam2204** [yadayada/acd_cli#37]
I tested the latest version on two different machine on different networks and it looks like upload speeds are unstable. I was able to reach an impressive peak of 41MB/s but it stays there for ~ 5 seconds to then drops to a far lower speed (sometime 5MB/s, 7MB/s, 20MB/s, etc.).

Download from what I've seen is even more unstable and didn't go over 17MB/s.

**Comment by yadayada** [comment]
In older versions, the speed was calculated as an average over the whole duration of the file transfer. Now, it's an average of the last 3 seconds.

There was a change I made to download in chunks of 50MB. That may affect you because your connection is obviously very fast and there is a waiting time before each request is sent.

Have you tried using multiple connections?

**Comment by Issam2204** [comment]
How can I achieve multiple connections?
