### ISSUE TITLE
Limit bandwidth?

### ISSUE THREAD

**Issue by alexreg** [yadayada/acd_cli#401]
Is there any way to limit the upstream/downstream bandwidth used for uploading/downloading files? If not, would you consider adding such a feature?

**Comment by dany20mh** [comment]
I have similar question, but mine is opposite of you and was wondering if that is possible to increase it in some other ways?

Like read more chunks at the same time or have more open connection to the Amazon server.

**Comment by gerph** [comment]
This applies to the CLI tool, not the FUSE FS:

The upload option has a '--max-connections' switch. This allows it to use multiple connections to simultaneously upload files to the servers, which does improve performance. However, it only applies to the file upload; the directory creation, which happens before files are upload remains single threaded.

**Comment by alexreg** [comment]
This doesn't help limit bandwidth though.

**Comment by gerph** [comment]
No, I was replying specifically to dany20mh's question to increase the bandwidth; sorry if that was not clear.

The generic solution to limiting bandwidth is to use traffic shaping, rather than building it in directly to the application. http://lartc.org/howto/lartc.ratelimit.single.html gives some examples on how you can do this on Linux to restrict the bandwidths used for a specific host. Presumably you can do it on Windows and OSX in similar ways, but I don't know those.

**Comment by alexreg** [comment]
Okay, thanks.

**Comment by dany20mh** [comment]
@gerph but that's only when you want to upload a file, what if you want to read few files and you want to have more connection.

**Comment by gerph** [comment]
@dany20mh The 'download' command also has a --max-connections switch, so I presume it can do the same. Can't say I've used the download more than to provide that, having uploaded, I can get the data back, so I don't know how much of an improvement it would gain. I would imagine that the amazon servers can probably outperform most local connections, and that bottlenecks are more likely to be caused by local contention. That said, if the connections were to different physical servers, it may improve things a lot more - can't say that I know what the situation is there.

**Comment by dany20mh** [comment]
@gerph 
But I don't use the download command and my other application using the volume so I don't know if something can be done inside the volume or fuse that increase the open connection.

**Comment by kehugter** [comment]
> The generic solution to limiting bandwidth is to use traffic shaping, rather than building it in directly to the application

Not really a scripting-friendly solution. Major data transfer tools normally provide a transfer rate limit option: `curl --limit-rate`, `wget --limit-rate`, `rsync --bwlimit`, `scp -l`, etc.

@yadayada no chances of implementing this?
