### ISSUE TITLE
Amazon Drive API Invite Only

### ISSUE THREAD

**Issue by kappa118** [yadayada/acd_cli#529]
This is more of a question than an issue: With Amazon Drive going [invite only](https://developer.amazon.com/amazon-drive) for its API, how will this affect the project? Were you able to get an invitation to build on top of the new API? Will the old API be phased out?

**Comment by yadayada** [comment]
I don't know what the changes to the API are or whether there are any to begin with. But I think this invitation-only business may only apply to Android and iOS applications. 

By the way, acd_cli got its production limits revoked in September last year (#416).

**Comment by Christoph-D** [comment]
No, it seems to be invite-only for everything, not only for Android and iOS apps.  Also as of March 13, 2017, they stopped giving out invites: https://forums.developer.amazon.com/questions/62280/how-to-get-invited-for-amazon-drive-development.html

This makes the acd_cli documentation seriously out of date because currently it looks impossible to get your security profile whitelisted.
