### ISSUE TITLE
Not my file 

### ISSUE THREAD

**Issue by thibrex** [yadayada/acd_cli#549]
Hi, 
My acd_cli has got a recent database corruption in node.db. I removed it and I executed "acd_cli sync".
But since that moment, I have the files of another person and I can download and see his files, upload and remove files! (Obviously I will not touch his files).
Is there not a problem in acd_cli ?
EDIT: I specify that even I remove the node.db, when I sync I have again the same cloud of this person
Thanks!

**Comment by yadayada** [comment]
Please contact (preferably phone) the Amazon support immediately.

**Comment by thibrex** [comment]
Ok I will call Amazon tomorrow concerning that. It's strange...

**Comment by thibrex** [comment]
Hi,
I called Amazon and they do not care, it's not their stuff because it's not their software...

**Comment by davidjameshowell** [comment]
I would assume that would be some type of Amazon Drive issue and not related to ACD_CLI due to the nature of how it is making federated requests with specific user data.

It may behoove you to get debug logs for listings and uploading files to that account to see the auth that is being generated for those requests. Definitely sounds suspicious though.

**Comment by thibrex** [comment]
I will send a mail with evidence to Amazon. I don't know really how works acd_cli but I think it's my API Key which have moved of owner maybe ?

**Comment by thenoahcomputer** [comment]
I suspect you got someone else's auth token somehow, but that should never ever happen or even be possible.  I would make a backup of your current oauth_data file (maybe that whole acd_cli cache folder it lives in), move it somewhere else, then re-authorize acd_cli. If you still see other people's files, I would raise holy hell with Amazon until they get the message that their authentication system is compromised.  If you see someone else's files, it's entirely possible they can see yours.

Don't expect much though even if you start seeing your own data again.  Amazon Drive has been very flaky since yesterday.

**Comment by nbyloff** [comment]
Since this feels like a weird stuff going on with ACD, I just started getting a 503 error, quota something or other, and can't access my files.

I went to the web UI, and it was throwing an error for a little bit. NOW it's responding with an interstitial saying welcome and I should start my free trial, even though I am logged in and have had an account for 8 months with 7TB of data on it.

**Comment by Axadiw** [comment]
couple days ago I've got the same behaviour using acd_cli

**Comment by Saren-Arterius** [comment]
Hi. I suddenly have access to other's files after I deleted the corrupted DB and sync. What the actual fuck??????????

**Comment by Saren-Arterius** [comment]
![image](https://cloud.githubusercontent.com/assets/4948919/26023962/3256a3ae-37fa-11e7-8425-ee0f07139c48.png)
![image](https://cloud.githubusercontent.com/assets/4948919/26023966/3b6b01e2-37fa-11e7-813b-59a880dc5a93.png)
![image](https://cloud.githubusercontent.com/assets/4948919/26023970/3ffc2a92-37fa-11e7-898b-74bffc9feb00.png)

**Comment by Saren-Arterius** [comment]
I have contacted aws-security@amazon.com and security@amazon.com

**Comment by madyoda** [comment]
Ouch. This could be pretty bad. Did you notice any reproducability steps?

**Comment by Saren-Arterius** [comment]
@madyoda Nope. It happen very randomly. First your DB somehow gets corrupted. Delete it, `acdcli sync`, then tada.

**Comment by madyoda** [comment]
@Saren-Arterius does the amazon web interface show your files?

**Comment by Saren-Arterius** [comment]
@madyoda The web interface is fine. Maybe acd_cli triggered this server side problem.

**Comment by thibrex** [comment]
I had exactly the same issue, with the same step to do the bug.

**Comment by madyoda** [comment]
@Saren-Arterius interesting - seems like it's some token thing. Keep us updated re: amazon email(s) 👍

**Comment by thenoahcomputer** [comment]
This is most likely a problem with authentication on Amazon's end.  Could be really bad if someone, for example, has an automated script backing up their system to a folder called "backup" and it deletes/replaces someone else's backup folder unnoticed after this glitch occurs.

Perhaps it's worth adding a basic sanity check to prevent since it's happened to more than just a couple people?  Maybe have acd_cli write a uuid to a file on acd_cli or otherwise fingerprint the account to ensure it is using the same account as the last time when it syncs nodes and throw a warning if there is a mismatch?

**Comment by skirsten** [comment]
So this is my take on this: The corrupted db is not the cause of this problem but rather a side effect.
I guess that during some regular request (upload, download, file list, etc.) the OAuth token got renewed but what amazon or the appspot authenticator returned was the renewed OAuth of somebody else.

I took a look at the [authenticator implementation](https://tensile-runway-92512.appspot.com/src) and it seems pretty solid, so maybe amazon screwed something up on their end.

I'm currently running a _get usage information, renew token, check if usage changed_ loop to reproduce this error but with no success at this time.

**Comment by M0V3** [comment]
Seems to me like this has something to do with the Rate Exceeded Error. Reports of both errors seem to come up at the same time.

**Comment by nbyloff** [comment]
When I look at the oauth code in acdcli, it uses an AppSpotAuthenticator. Why? Can't authentication be done using a more common OAuth setup?

**Comment by skirsten** [comment]
@nbyloff Authorization using the Google App Engine (AppSpot) "proxy" is used for simplicity. You can setup a local OAuth callback and use that, see [Authorization](https://github.com/yadayada/acd_cli/blob/master/docs/authorization.rst).

**Comment by PlasmaPower** [comment]
Has anyone attempted to contact the user whose files they received and find out if they use `acd_cli`?

**Comment by Saren-Arterius** [comment]
Their security team replied. I hope this issue can be fixed sooner...

**Comment by davidjameshowell** [comment]
So it was deemed to be an issue on Amazon's authentication side? An actual
issue?

**Comment by Saren-Arterius** [comment]
@davidjameshowell They did not confirm, but I guess it should be...

**Comment by madyoda** [comment]
@Saren-Arterius any idea what they said? If you visit  https://tensile-runway-92512.appspot.com/ now, it says unknown client_id. Almost seems like acd_cli got revoked from Amazon.

**Comment by SchnorcherSepp** [comment]
I learned from Amazon: just wait and see
Give the security team some time....

**Comment by Saren-Arterius** [comment]
@madyoda 
```
To help us have a full understanding of your report (HG027509461), can you please let us know when exactly did you start experiencing this issue?

Could you please also tell us how you initially authenticated to Amazon Cloud Drive using acd_cdi? I can see different methods described on https://acd-cli.readthedocs.io/en/latest/authorization.html.
```
Seeing acd_cli no longer works possibly because of this, I somehow feel guilty lol.

**Comment by madyoda** [comment]
@Saren-Arterius I wouldn't feel guilty - you potentially stopped a big issue i.e. people accessing each others accounts. I'd mention you used tensile-runway-92512.appspot.com and that's hosted on the Google App Engine.
(I also don't know if it's public info but you may want to remove the report ID in the brackets (HG....))

**Comment by Saren-Arterius** [comment]
@madyoda Thanks for reminding that, the ID is removed.

**Comment by nob0dy80** [comment]
shame on you @Saren-Arterius  ... since acdcli is down and i cant access my encrypted media files i feel kind of prehistoric :-)
If acdcli wont come back i would be kind of lost since i dont know a other way to mount the drive into a folder on linux :-/

**Comment by madyoda** [comment]
@nob0dy80 take a look at [rclone](http://rclone.org), specifically [this](https://rclone.org/commands/rclone_mount/)

**Comment by Saren-Arterius** [comment]
@nob0dy80 rofl didn't expect that

**Comment by nob0dy80** [comment]
@Saren-Arterius everythine fine... security first. not your fault at all .. but i hope it will come back, worked great for me.

@madyoda ...oh ..didnt know there is a mount option on rclone. But don't like the word "experimental" when playing arround with my media. But i'll give it a try. Hope the performance is compareable to acdcli.

**Comment by JulianMiribel** [comment]
Same issue here.

Tried to setup an amazon profile but it seems amazon won't allow API access anymore so I'm stuck.

@Saren-Arterius no worries, I'm more than pleased to know a security hole might be fixed.

**Comment by nob0dy80** [comment]
@madyoda thanks again for the hint. testet it now. what can i say. the bufferunderruns with large video files i had with acdcli are gone and the mounting process is arround 300% faster (cause i dont need to resync my database to see new files in my encrypted mount). 
since i used acdcli only for the mount, i dont see a reason to use it any longer if rclone handles it so well.
Lets see how it works in a longer time period....

**Comment by madyoda** [comment]
@nob0dy80 yep I am a big fan of rclone 👍 an idea: when (if 😢) acd_cli comes back, setup a unionfs mount with both the rclone mount plus acd_cli mount for extra redundancy if something like this happens again. It's what I'm going to be doing myself, as well as mirroring my stuff over to Google Drive too and setting up a third "redundant" place.

**Comment by madyoda** [comment]
On another note...  
![image](https://cloud.githubusercontent.com/assets/5332144/26034315/9f9fea66-38b2-11e7-986e-b81700f374ac.png)

**Comment by Giantdouche33** [comment]
any word from Amazon on this issue?

**Comment by madyoda** [comment]
@Giantdouche33 @Saren-Arterius would be the one to ask, though it's a Sunday so I wouldn't expect much until tomorrow.

**Comment by Saren-Arterius** [comment]
@Giantdouche33 not yet since I replied

**Comment by scriptzteam** [comment]
well well well, seems its better to use rclone ;) BTW crypt everything :D

**Comment by yadayada** [comment]
I put up a fixed version of the Appspot app, see http://acd-api-oa.appspot.com/src.

**Comment by beam** [comment]
So this was oauth problem? What was the problem exactly?
Can you give us diff (on gist maybe) between new appspot and old one?

**Comment by yadayada** [comment]
@beam Yes. See https://github.com/yadayada/acd_api_oauth.

**Comment by pink-mist** [comment]
Considering the new oauth solution, perhaps this can be closed?
