### ISSUE TITLE
Support writing to fuse mount

### ISSUE THREAD

**Issue by HazCod** [yadayada/acd_cli#77]
Now that we have support for reading from the mount, only thing missing is providing transparent write access. (Feature request)

**Comment by yadayada** [comment]
This is somewhat related to the streamed upload API-wise (#75).

**Comment by cpare** [comment]
+1 for this enhancement

**Comment by cpare** [comment]
Hey yadayada - any way we can support you with this change?  Pizza and Red Bull perhaps?
Honestly, if there was a way I could donate to this this feature faster I would be happy to.

**Comment by hongkongkiwi** [comment]
:+1:  for donating for development :-)

**Comment by yadayada** [comment]
If you want, you can add special instructions when you make a donation to https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=V4V4HVSAH4VW8.

Besides other, more pertinant reasons, I haven't started implementing this because I'm not completely sure that FUSE writes can be done using simple streamed uploads. Maybe a cached write is necessary, like acd_fuse seems to be doing.

**Comment by hongkongkiwi** [comment]
@yadayada Great! I made a small donation for you :-) Keep up the great work!

**Comment by kelna** [comment]
Is there any news on this topic? This is really the last (but most) important feature.

**Comment by yadayada** [comment]
I think I finally can get something done about this on next weekend. I'll let you know whether the concept  works or not by next week.

**Comment by xHN35RQ** [comment]
:+1:

**Comment by cpare** [comment]
Has this commit been verified?  I am ready to go home and get this installed!

**Comment by yadayada** [comment]
It works for me™. I'll push it to the master branch soon.

**Comment by JDogHerman** [comment]
Can't wait to try it. Thanks @yadayada 

...sending donation soon
