### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by LtRipley36706** [yadayada/acd_cli#85]
Currently I'm unable to complete the initial sync after getting the oauth data. It errors out with either Connection reset by peer or IncompleteRead. I can provide logs as needed but I suspect the reason is due to a significant number of files/directories on the ACD account I'm using. Perhaps the code is timing out on the response or the data coming in is far larger than expected?

Any ideas on how to resolve this?

**Comment by resipsa2917** [comment]
See https://github.com/yadayada/acd_cli/issues/74.  Strange that you are still getting the error, but it was something amazon did, but should be fixed by now.

**Comment by resipsa2917** [comment]
Could be a different error though.... I say provide the log.

**Comment by yadayada** [comment]
I have to tell you beforehand: the errors you get are low-level ones and this is most likely out of my reach.

You might want to try ``acdcli old-sync``.

- What is you operating system? 
- How many files/directories do you have? How much storage is used?
- Please post the log messages.

**Comment by LtRipley36706** [comment]
I'll give old-sync a try and report back... What does that do differently?

OS: Ubuntu 14.04.2
ACD reports 620k files, 5.6 TB. It doesn't tell me how many folders it has but I guess it to be upwards of 80k as that is how many are in the source I uploaded from.
Logs to follow tonight.

Thanks for your assistance :)

**Comment by LtRipley36706** [comment]
> 15-07-10 15:36:10.365 [DEBUG] [acdcli.cache.sync] - {'labels': [], 'createdBy': 'CloudDriveDesktop', 'createdDate': '2015-06-02T17:21:49.856Z', 'name': 'Season 1', 'version': 31, 'id': 'q726CzjVTbegDB77MaasTg', 'isShared': False, 'description': 'Atmos\\TV\\UnREAL\\Season 1', 'modifiedDate': '2015-07-07T17:23:48.345Z', 'parents': ['5esIYnqTTqSRYHTUTV8aWA'], 'kind': 'FOLDER', 'eTagResponse': 'tBG-mSk5huI', 'status': 'AVAILABLE', 'restricted': False}
> 15-07-10 15:36:11.064 [INFO] [acdcli.cache.sync] - Inserted/updated 82761 folders.
> Killed
The above was the end result of running old-sync before I headed out the door. Not sure how long it ran but I'm executing it again now before moving on to see if I can proceed to use other parts of the program. Definitely got farther than standard sync so far.

**Comment by LtRipley36706** [comment]
Ultimately I kept getting errors like this:

> 15-07-11 01:26:30.158 [CRITICAL] [acd_cli] - Sync failed.
RequestError: 500, {"logref":"5dd28e02-278d-11e5-98e1-6333332f4b36","message":"Internal Server Error"}
Done.

I decided to delete folders that I hadn't modified since originally uploading just to see if I could get to a point where the 500 error stopped. Eventually I got down to 60k in files and the sync completed successfully at that point. 

I plan to re-upload those folders I deleted starting next week to see if the problem returns. I have a feeling however it actually wasn't the number of files/folders being too large but perhaps one file specifically that might have been the culprit. It could be that the file was too large (20GB) but I'm not convinced. The file is a image of an original Xbox 360 hard drive and I think I recall there being a problem initially uploading it anyway, for what its worth.

Either way likely not something that can be solved on this end of things.

**Comment by yadayada** [comment]
The old-sync is "paginated" and gets 200 nodes per request... which admittedly is not very sensible for such a large amount of files.

I will also try to reproduce this by generating a few 100K of files.

**Comment by LtRipley36706** [comment]
Re-uploaded the folders I deleted minus the one file that I suspecting being issue and I was still able to sync. I think at this point it safe to say it wasn't the amount of folders/files but just one corrupt file.

**Comment by Harrdy** [comment]
Have the same problems since yesterday evening

eu account

[CODE]17-05-14 08:03:22.881 [DEBUG] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): drive.amazonaws.com
17-05-14 08:03:23.420 [DEBUG] [requests.packages.urllib3.connectionpool] - https://drive.amazonaws.com:443 "GET /drive/v1/account/endpoint HTTP/1.1" 429 47
17-05-14 08:03:23.429 [CRITICAL] [acdcli.api.client] - Error getting endpoint data. Response: {"message":"Rate exceeded"}[/CODE]

my second try from a other location

[CODE]17-05-14 08:03:09.580 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.001677s
17-05-14 08:03:09.580 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.eu-west-1.amazonaws.com/drive/v1/changes"
17-05-14 08:03:09.580 [DEBUG] [acdcli.api.backoff_req] - {}
17-05-14 08:03:09.581 [DEBUG] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.eu-west-1.amazonaws.com
17-05-14 08:03:09.674 [DEBUG] [requests.packages.urllib3.connectionpool] - https://cdws.eu-west-1.amazonaws.com:443 "POST /drive/v1/changes HTTP/1.1" 429 71
[/CODE]

rclone still works
